library(tidyverse)

# load example data generated by random_data_generator.R
df <- read_csv("example.csv")

# explore data
glimpse(df)

# print out number of missing values for each variable
df %>% 
  summarise_all(funs(sum(is.na(.)))) %>% 
  t(.)

# replace or remove all missing values
df <- 
  df %>% 
  # replace missing values
  mutate(officer = ifelse(is.na(officer), "unassigned", officer),
         proposal  = ifelse(is.na(proposal), 0, proposal),
         priority  = ifelse(is.na(priority), "none",  as.character(priority)),
         status = ifelse(is.na(status), "pending", status),
         # create indicator for missing rating before imputing to 0
         no_rating = ifelse(is.na(rating), 1, 0),
         rating = ifelse(is.na(rating), 0, rating)) %>% 
  # limit to only alumni
  filter(!is.na(class)) %>% 
  select(-constituency)

# create id variable
df$id <- 1:nrow(df)

# create binary giving indicators
# df <- 
#   df %>% 
#   mutate_at(.vars = vars(matches('af|cap')),
#             .funs = list(binary = function(x) ifelse(x > 0, 1, 0)))
# 


